name: Clean DO Registry

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Install latest Yarn
        run: |
          corepack prepare yarn@stable --activate
          yarn set version stable
          yarn --version

      - name: Get yarn cache directory
        id: yarn-cache
        shell: bash
        run: |
          echo "YARN_CACHE_PATH=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup yarn cache
        with:
          path: ${{ steps.yarn-cache.outputs.YARN_CACHE_PATH }}
          key: ${{ runner.os }}-yarn-cache-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            ${{ runner.os }}-yarn-cache-

      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Run clean script
        run: |
          yarn run clean-do-registry
